In [6]:
!pip install gensim

In [7]:
from gensim.models import Word2Vec,KeyedVectors

In [8]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

In [9]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [10]:
vec_king.shape

(300,)

In [11]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [12]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [13]:
wv.similarity("Hi","Hello")

np.float32(0.61887926)

In [14]:
vec=wv['king']-wv['man']+wv['woman']

In [15]:
print(vec)

[ 4.29687500e-02 -1.78222656e-01 -1.29089355e-01  1.15234375e-01
  2.68554688e-03 -1.02294922e-01  1.95800781e-01 -1.79504395e-01
  1.95312500e-02  4.09919739e-01 -3.68164062e-01 -3.96484375e-01
 -1.56738281e-01  1.46484375e-03 -9.30175781e-02 -1.16455078e-01
 -5.51757812e-02 -1.07574463e-01  7.91015625e-02  1.98974609e-01
  2.38525391e-01  6.34002686e-02 -2.17285156e-02  0.00000000e+00
  4.72412109e-02 -2.17773438e-01 -3.44726562e-01  6.37207031e-02
  3.16406250e-01 -1.97631836e-01  8.59375000e-02 -8.11767578e-02
 -3.71093750e-02  3.15551758e-01 -3.41796875e-01 -4.68750000e-02
  9.76562500e-02  8.39843750e-02 -9.71679688e-02  5.17578125e-02
 -5.00488281e-02 -2.20947266e-01  2.29492188e-01  1.26403809e-01
  2.49023438e-01  2.09960938e-02 -1.09863281e-01  5.81054688e-02
 -3.35693359e-02  1.29577637e-01  2.41699219e-02  3.48129272e-02
 -2.60009766e-01  2.42309570e-01 -3.21777344e-01  1.45416260e-02
 -1.59179688e-01 -8.37402344e-02  1.65039062e-01  1.58691406e-03
  3.09570312e-01  3.16406

In [16]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [17]:
import pandas as pd
import numpy as np
df = pd.read_csv("SMSSpamCollection.txt", sep='\t', names=["label","messages"])

In [18]:
from nltk.stem import WordNetLemmatizer

In [21]:
lemmatizer=WordNetLemmatizer()

In [24]:
import re
import nltk
nltk.download('stopwords')



[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sumit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [27]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['messages'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [28]:
print(corpus)

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat', 'ok lar joking wif u oni', 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s', 'u dun say so early hor u c already then say', 'nah i don t think he go to usf he life around here though', 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv', 'even my brother is not like to speak with me they treat me like aid patent', 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune', 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only', 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co f

In [34]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [35]:
#simple_preprocess()

TypeError: simple_preprocess() missing 1 required positional argument: 'doc'

In [38]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [39]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [40]:
import gensim 

In [41]:
#lets train word2vec from scratch
model=gensim.models.Word2Vec(words,vector_size=100)

In [43]:
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope

In [44]:
model.corpus_count

5569

In [47]:
model.epochs

5

In [48]:
model.wv.similar_by_word('kid')

[('eat', 0.9979444146156311),
 ('other', 0.9978405833244324),
 ('check', 0.9978319406509399),
 ('abt', 0.9978063106536865),
 ('dinner', 0.9978020191192627),
 ('im', 0.9977843761444092),
 ('which', 0.9977782368659973),
 ('lol', 0.997776210308075),
 ('better', 0.9977724552154541),
 ('nite', 0.9977459907531738)]

In [49]:
model.wv['good']

array([-0.28461027,  0.3516552 ,  0.0508431 ,  0.17483005,  0.08001031,
       -0.737304  ,  0.14941144,  0.6308622 , -0.4157871 , -0.10869659,
       -0.31987542, -0.6125267 ,  0.05401325,  0.15471463,  0.274386  ,
       -0.20928892,  0.17432615, -0.40292627, -0.04113735, -0.78310513,
        0.3354745 ,  0.30773416,  0.20093808, -0.28096297, -0.11994634,
       -0.03620222, -0.50696117, -0.27721968, -0.4036705 ,  0.00903733,
        0.48645377,  0.03917588,  0.1661176 , -0.31922844, -0.20818247,
        0.51150984, -0.0149182 , -0.24286067, -0.21637626, -0.6106361 ,
        0.19188365, -0.36255434, -0.2500079 ,  0.07165812,  0.3862075 ,
       -0.01968969, -0.37502712, -0.17847465,  0.12502617,  0.23728107,
        0.29479843, -0.20620044, -0.10031044,  0.03372322, -0.10388131,
        0.2523863 ,  0.29481643,  0.0486294 , -0.445496  ,  0.19248742,
       -0.11150788,  0.1653055 , -0.14931402, -0.18409657, -0.5263114 ,
        0.39252847,  0.02722735,  0.20771755, -0.48278755,  0.43

In [81]:

def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)


In [82]:
!pip install tqdm

In [83]:
from tqdm import tqdm

In [84]:
#apply forn the entire sentence
X=[]
for i in tqdm(range(len(words))):
    X.append(avgword2vec(words[i]))

100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:01<00:00, 5331.17it/s]


In [85]:
X

[array([-0.19956198,  0.2413015 ,  0.04897196,  0.12765393,  0.06039383,
        -0.55317706,  0.1035882 ,  0.44105244, -0.29650193, -0.08867233,
        -0.2377393 , -0.4193894 ,  0.00078359,  0.11082064,  0.20898727,
        -0.14894539,  0.11874154, -0.29479638, -0.03485468, -0.5553867 ,
         0.20585789,  0.21054928,  0.12607251, -0.19923979, -0.08472794,
        -0.02165527, -0.3912949 , -0.20652018, -0.28049853,  0.01483425,
         0.35128912,  0.03836719,  0.10457224, -0.21883018, -0.14493775,
         0.36766806,  0.00885358, -0.18607497, -0.16825417, -0.44181374,
         0.1361907 , -0.26191494, -0.18981533,  0.03266849,  0.28301767,
        -0.02319049, -0.25908908, -0.11075824,  0.11547131,  0.17042463,
         0.17959824, -0.15455937, -0.05440675,  0.06323668, -0.1051629 ,
         0.18396671,  0.1971382 ,  0.03198425, -0.3191481 ,  0.15261784,
        -0.0631372 ,  0.12607796, -0.08472633, -0.13080394, -0.3590369 ,
         0.2800293 ,  0.01762533,  0.14234759, -0.3

In [86]:
df.shape

(5572, 2)

In [87]:
#independent feature
X_new=np.array(X)

In [88]:
X_new.shape

(5569, 100)

In [89]:
X_new[0].shape

(100,)

In [91]:
## Dependent Features
## Output Features
y = df[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values

In [92]:
y.shape

(5569,)

In [93]:

X[0].reshape(1,-1).shape

(1, 100)

In [97]:
X = []
for i in range(len(words)):
    X.append(avgword2vec(words[i]))

df = pd.DataFrame(X)

In [98]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.199562,0.241302,0.048972,0.127654,0.060394,-0.553177,0.103588,0.441052,-0.296502,-0.088672,...,0.274871,0.166626,0.038427,0.106022,0.315812,0.340537,0.095483,-0.197078,0.150644,-0.073189
1,-0.172902,0.206485,0.041785,0.116169,0.048124,-0.488510,0.081884,0.387554,-0.250704,-0.063552,...,0.240558,0.140523,0.029299,0.087785,0.270948,0.285838,0.078321,-0.180313,0.124042,-0.063552
2,-0.196543,0.252038,0.065574,0.161520,0.063568,-0.608854,0.111944,0.443732,-0.318676,-0.101294,...,0.270576,0.174785,0.017948,0.102841,0.325707,0.327087,0.064340,-0.219764,0.176555,-0.067210
3,-0.268121,0.325414,0.060459,0.171945,0.074453,-0.733914,0.137189,0.597846,-0.400245,-0.110686,...,0.369479,0.218519,0.050865,0.146894,0.415361,0.459027,0.131912,-0.270728,0.194823,-0.093353
4,-0.235824,0.268911,0.059358,0.140243,0.079063,-0.621523,0.108198,0.506728,-0.340897,-0.103100,...,0.322716,0.180713,0.042115,0.121848,0.345809,0.391089,0.106167,-0.238369,0.165262,-0.085925


In [99]:
df['output']=y

In [100]:
df.dropna(inplace=True)

In [101]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
output    0
Length: 101, dtype: int64

In [109]:
X=df.drop('output', axis=1)

In [110]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [111]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [112]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
4728,-0.218864,0.247710,0.044392,0.132200,0.068583,-0.569628,0.091936,0.453391,-0.310165,-0.086364,...,0.290352,0.168992,0.042572,0.104287,0.308939,0.353007,0.103687,-0.214310,0.156060,-0.066395
5427,-0.260809,0.298133,0.062491,0.152653,0.088789,-0.690556,0.119603,0.568389,-0.378226,-0.126637,...,0.367725,0.198586,0.051766,0.125405,0.381233,0.437952,0.118895,-0.260392,0.184024,-0.088334
4455,-0.248964,0.289031,0.057353,0.142676,0.080132,-0.657454,0.113215,0.532866,-0.362784,-0.113738,...,0.339735,0.194378,0.048927,0.120659,0.369193,0.416822,0.115994,-0.246638,0.178672,-0.083767
1577,-0.260232,0.320352,0.066281,0.179067,0.071155,-0.741134,0.140063,0.595005,-0.392264,-0.121202,...,0.368583,0.219235,0.056703,0.140231,0.426390,0.451445,0.114220,-0.263945,0.204626,-0.099490
5312,-0.253558,0.329795,0.080323,0.179514,0.086540,-0.746601,0.129677,0.582148,-0.392276,-0.130392,...,0.364805,0.223554,0.039766,0.136657,0.412721,0.438781,0.123787,-0.273538,0.211979,-0.097844


In [113]:
y_train

array([ True,  True,  True, ...,  True,  True,  True], shape=(4455,))

In [114]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [115]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [116]:
y_pred=classifier.predict(X_test)

In [117]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [119]:
print(accuracy_score(y_pred,y_test))

0.9578096947935368


In [120]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.80      0.90      0.85       146
        True       0.98      0.97      0.98       968

    accuracy                           0.96      1114
   macro avg       0.89      0.93      0.91      1114
weighted avg       0.96      0.96      0.96      1114



In [121]:
print(confusion_matrix(y_test,y_pred))

[[131  32]
 [ 15 936]]
